---Taller 2-2 requerimiento #3

SELECT TABLE_NAME AS NOMBRETABLA, DATA_TYPE AS TIPODEDATOS, COUNT(DATA_TYPE) AS NUMCOLSTIPODATO, ROUND(AVG(avg_col_len),2) AS PROMEDIOLONGITUDCOL
FROM ALL_TAB_COLUMNS cols
WHERE owner = 'PARRANDEROS'
GROUP BY TABLE_NAME, DATA_TYPE
ORDER BY TABLE_NAME ASC;
