---Taller 2-2 requerimiento #4
SELECT COLS.TABLE_NAME AS NOMBRETABLA, 
       COLS.COLUMN_NAME AS NOMBRECOLUMNA, 
       COLS.DATA_TYPE AS TIPODEDATO, 
       DECODE(COLS.NULLABLE, 'Y', 'SI', 'N', 'NO') AS PERMITENULO,
       DECODE(CON.CONSTRAINT_NAME, NULL, 'NO TIENE', CON.CONSTRAINT_NAME) AS NOMBRERESTRICCION
FROM USER_TAB_COLUMNS COLS
LEFT JOIN (
    SELECT UC.TABLE_NAME, UC.COLUMN_NAME, UC.CONSTRAINT_NAME
    FROM USER_CONS_COLUMNS UC
    JOIN USER_CONSTRAINTS C ON UC.CONSTRAINT_NAME = C.CONSTRAINT_NAME AND C.CONSTRAINT_TYPE = 'C') CON 
    ON COLS.TABLE_NAME = CON.TABLE_NAME AND COLS.COLUMN_NAME = CON.COLUMN_NAME
WHERE COLS.TABLE_NAME IN ('BARES', 'BEBEDORES', 'BEBIDAS', 'FRECUENTAN', 'GUSTAN', 'SIRVEN', 'TIPO_BEBIDA')
ORDER BY COLS.TABLE_NAME, COLS.COLUMN_NAME, CON.CONSTRAINT_NAME;
