
---Taller 2-2 requerimiento #1
SELECT TABLE_NAME AS NOMBRETABLA, 
       COUNT(*) AS NUMCOLUMNAS, 
       SUM(CASE WHEN NULLABLE='Y' THEN 1 ELSE 0 END) AS NUMCOLSNULL, 
       LAST_ANALYZED AS ÚLTIMO_ANÁLISIS 
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME IN ('BARES', 'BEBEDORES', 'BEBIDAS', 'FRECUENTAN', 'GUSTAN', 'SIRVEN', 'TIPO_BEBIDA')
GROUP BY TABLE_NAME, LAST_ANALYZED 
ORDER BY TABLE_NAME;




